version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"