spring:
  application:
    name: bucket4j
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0